### ISSUE TITLE
Remove or change nav bar in the About and Robot pages

### ISSUE THREAD

**Issue by evanmhm** [SouthEugeneRoboticsTeam/SouthEugeneRoboticsTeam.github.io#11]
I think it's a little funky to have the same nav bar even though the pages are removed from the main page.

**Comment by andrewda** [comment]
Actually, if we just added the about and robots page it might be better.

**Comment by evanmhm** [comment]
Maybe put the about and robot stuff page together in one seperate page with it's  own Nav bar with buttons for About Robots and Home. Then on the main page nav bar have a button for More Info

**Comment by andrewda** [comment]
Hmm ok I'll see what works best. I don't really like changing the nav bar since it means a lot of logic in the template and we could probably find something that works well on every page.

**Comment by evanmhm** [comment]
Not really an issue anymore because of ea8c6ea7e3bc0f8a91ecdb248fe4d9d927e906dc
