### ISSUE TITLE
Add menu to small screens!!!

### ISSUE THREAD

**Issue by SUPERCILEX** [SouthEugeneRoboticsTeam/SouthEugeneRoboticsTeam.github.io#31]
We still don't have this working on mobile! Right now you can only navigate to the first page of SERT's website on small screens. 😢

**Comment by andrewda** [comment]
Yea this is very much needed – I'll try working on that now.

**Comment by andrewda** [comment]
:eyes:

**Comment by SUPERCILEX** [comment]
Just closing out old issues lol

**Comment by InquisitivePenguin** [comment]
Wow this takes me back. Good times.
