### ISSUE TITLE
Add contact information

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/SouthEugeneRoboticsTeam.github.io#42]
It's very difficult to find contact information on the website. We might not even have any on the website right now. This is an issue.

**Comment by SUPERCILEX** [comment]
We have it here:
![image](https://user-images.githubusercontent.com/9490724/33922660-13c31dc6-df81-11e7-89bf-d4b6d6b87ea7.png)

**Comment by andrewda** [comment]
Phone number would be nice too. Also a bigger email address.

**Comment by SUPERCILEX** [comment]
Alex also pointed out that we should have general team meeting hours.

**Comment by andrewda** [comment]
Good point
